version: '3.8'

services:
  # The Python/Flask microservice
  web:
    build: .  # Build the image from the Dockerfile in the current directory
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    environment:
      # Pass database connection details to the app
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=db # This is the service name of our database container
      - DB_NAME=valorant_stats
    depends_on:
      - db # Wait for the db service to be ready before starting web

  # The PostgreSQL database service
  db:
    image: postgres:14-alpine # Use an official PostgreSQL image
    environment:
      # These variables are used by the Postgres image to initialize the database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=valorant_stats
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

volumes:
  postgres_data: # Define the named volume